baseURL = "https://kravie403.github.io/"  # 도메인을 설정하세요
languageCode = "ko"  # 기본 언어를 한국어로 설정
title = "Portfolio"  # 사이트 제목

[params]
  description = "The **Research Group Template** empowers your research group to easily create a beautiful website with a stunning homepage, news, academic publications, events, team profiles, and a contact form."
  author = "George Cushen"
  homepage = "https://github.com/wowchemy/starter-hugo-research-group"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/home"
    weight = 10

  [[menu.main]]
    identifier = "welcome"
    name = "Welcome"
    url = "/home/welcome"
    parent = "home"
    weight = 1

  [[menu.main]]
    identifier = "latest-updates"
    name = "Latest Updates"
    url = "/home/latest-updates"
    parent = "home"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20

  [[menu.main]]
    identifier = "biography"
    name = "Biography"
    url = "/about/biography"
    parent = "about"
    weight = 1

  [[menu.main]]
    identifier = "mission-vision"
    name = "Mission & Vision"
    url = "/about/mission-vision"
    parent = "about"
    weight = 2

  [[menu.main]]
    identifier = "skillset"
    name = "SkillSet"
    url = "/skillset"
    weight = 30

  [[menu.main]]
    identifier = "technical-skills"
    name = "TechnicalSkills"
    url = "/skillset/technical-skills"
    parent = "skillset"
    weight = 1

  [[menu.main]]
    identifier = "soft-skills"
    name = "SoftSkills"
    url = "/skillset/soft-skills"
    parent = "skillset"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 40

  [[menu.main]]
    identifier = "main-projects"
    name = "MainProjects"
    url = "/projects/main-projects"
    parent = "projects"
    weight = 1

  [[menu.main]]
    identifier = "sub-projects"
    name = "SubProjects"
    url = "/projects/sub-projects"
    parent = "projects"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 50

  [[menu.main]]
    identifier = "contact-form"
    name = "ContactForm"
    url = "/contact/form"
    parent = "contact"
    weight = 1

  [[menu.main]]
    identifier = "social-media"
    name = "SocialMediaLinks"
    url = "/contact/social-media"
    parent = "contact"
    weight = 2
